
name: CI
on:
  push:
    branches:
      - main
      - feature/**
    paths-ignore:
      - '.github/workflows/*'
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Static code analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install install -r requirements/prod.txt
        pip install -r requirements/dev.txt

    - name: run analysis with pylint
      run: |
        pylint --fail-under=8 microsvc/*

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: run unit tests
      run: |
        docker build --target test .

  build:
    name: Build container image and push to ECR
    runs-on: ubuntu-latest
    if: startsWith(github.ref_name,'v')
    outputs:
      image:  ${{ steps.build-image.outputs.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      run: |
        docker build -t ${{ secrets.ECR_REPOSITORY_URL }}:${{ github.ref_name }} .
        docker push ${{ secrets.ECR_REPOSITORY_URL }}:${{ github.ref_name }}
